version: '3.9'

services:
  nvst-react:
    build: .
    container_name: nvst-react
    image: nvst-react:latest
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 3000:3000
    volumes:
      - ${PWD}:/app